jobs:
  update:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      with:
        fetch-depth: 0
    - name: "Rebase to main"
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git switch gh-pages
        git rebase -X theirs main
    - name: "Update packages"
      uses: "radxa-repo/apt-repo-action@main"
      with:
        organization: "radxa-pkg"
        token: "${{ secrets.GITHUB_TOKEN }}"
    - id: "git-check"
      name: "Check for modified files"
      run: |
        echo "modified=$([ -z "$(git status --porcelain)" ]; echo $?)" >> "$GITHUB_OUTPUT"
    - if: "steps.git-check.outputs.modified == 1"
      name: "Commit changes"
      run: |
        cat << EOF | gpg --import
        ${{ secrets.GPG_KEY }}
        EOF
        freight cache
        git add .
        git commit -m "Update packages"
        git push -f
name: "Update packages"
"on":
  repository_dispatch:
    types:
    - "new_package_release"
  workflow_dispatch: {}
  workflow_run:
    types:
    - "completed"
    workflows:
    - "Reset APT repo"