jobs:
  update:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      with:
        repository: "RadxaOS-SDK/rsdk"
    - env:
        GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      id: "build"
      name: "Build apt archive"
      run: |
        sudo apt-get update
        sudo apt-get install -y aptly
        
        cat << EOF | gpg --import
        ${{ secrets.GPG_KEY }}
        EOF
        cat << EOF | gpg --import
        ${{ secrets.RADXA_APT_KEY_2024 }}
        EOF
        
        suites=("sid-test")
        
        src/bin/rsdk infra-pkg-snapshot
        src/bin/rsdk infra-pkg-download "${suites[@]}"
        src/bin/rsdk infra-repo-build "${suites[@]}"
        echo "pages='$(realpath ~/.aptly/public/rsdk-local/)'" >> $GITHUB_OUTPUT
      shell: "bash"
    - name: "Setup Pages"
      uses: "actions/configure-pages@v5"
    - name: "Upload artifact"
      uses: "actions/upload-pages-artifact@v3"
      with:
        path: "${{ steps.build.outputs.pages }}"
    - if: "github.event_name != 'pull_request'"
      name: "Deploy to GitHub Pages"
      uses: "actions/deploy-pages@v4"
name: "Update packages"
"on":
  repository_dispatch:
    types:
    - "new_package_release"
  workflow_dispatch: {}
permissions: {}